import Head from "next/head"

export default function Home() {
	return (
		<>
			<Head>
				<title>Fem-pedia</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="text-9xl font-bold">Hello World!</main>
		</>
	)
}
