import Head from "next/head"
import CategoryBoard from "../components/CategoryBoard"
import TodayFeed from "../components/TodayFeed"

export default function Home() {
	return (
		<>
			<Head>
				<title>Fem-pedia</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="grid grid-cols-2 gap-4">
				<TodayFeed />
				<CategoryBoard />
			</div>
		</>
	)
}
